fix: mssql should only load data for the views specified by materialize views
dimitri/pgloader pull request #1559
Opened 2024-02-21 01:38 UTC by conoremclaughlin

2024-02-21 07:37 UTC, svantevonerichsen6906 requested changes
Please don't litter the code base with debugging prints, and please do adhere to the formatting standard that is very much established in the entire Lisp language ecosystem.  Can't review like this.

2024-03-08 04:46 UTC, conoremclaughlin commented
Hi @svantevonerichsen6906, thanks for the comments. I wanted to get the PR up for anyone who found it useful before cleaning it up.

I've removed the debug statements and have changed the parentheses to follow more of Lisp's standards. Unfortunately it's been quite some time since I learned Lisp in Berkeley and Lisp doesn't have a good formatter, so this is about as far as I can go. Otherwise I would run the formatter across the file. The original code specifically notes that this flow was untested by the author, so anything is an improvement over the untested / completely broken materialize views code path we currently have for MSSQL.

Thanks!

2024-03-11 20:43 UTC, conoremclaughlin commented
Fixes #1551.

2024-06-17 13:32 UTC, conoremclaughlin commented
Bumping this @svantevonerichsen6906. Thanks man!

2024-06-17 14:01 UTC, svantevonerichsen6906 commented on src/sources/mssql/mssql.lisp
> +          (push-to-end view-name (cdr schema-entry))))
What I mean is: completely clean up the debugging alterations, and this is the indentation that should appear here:

```
(let* ((view-names (unless (eq :all materialize-views)
                     (mapcar #'matview-source-name materialize-views)))
       (including nil))
  (loop :for (schema-name . view-name) :in view-names
        :do (let* ((schema-name (or schema-name "dbo"))
                   (schema-entry (or
                                  (assoc schema-name including :test #'string=)
                                  (let ((new-entry (cons schema-name nil)))
                                    (push new-entry including)
                                    new-entry))))
              (push-to-end view-name (cdr schema-entry))))
  …)
```

I don't fully understand what's changed here yet, though

2026-06-25 21:07 UTC, dimitri commented
Thanks for the fix, @conoremclaughlin — the diagnosis was correct.

This was properly resolved as part of a broader cleanup in #1720 (merged 2026-06-23). The clean fix uses a separate `view-including` alist built from `(copy-tree including)` plus the view names, leaving the outer `including` filter untouched for `fetch-indexes` and `fetch-foreign-keys`. A regression test (`filtertest` database, `09-filter-views-counts`, `10-filter-views-integrity`) was added at the same time to prevent it regressing.

Closing in favour of that work.

2026-06-25 21:07 UTC, closed without merging